### PR TITLE
Remote processing added, on-device removed

### PR DESCRIPTION
**Pull request by carpenterd777**
I started on this issue but was unable to finish it up in time. Feel free to try and pick up where I left off!
The main issue seemed to be that the remote server would not accept the request made from my phone, but I think that should have been fixed in #72.
- Add axios
- post image to remote server
- edit server route
- remove loading of model
- remove reference to model
- make call to remote server

### CODE REVIEW

**Review by dyc3 — COMMENTED** [review]
I see we still need to convert the image to base 64. We can forego fixing that in this PR, but is there a way we could avoid doing that?

**Comment by dyc3** [comment]
I managed to fix the file upload, with the added benefit of not converting to base64 first. I tested it running the api server locally. I did notice that one time, image processing on the server took forever (>5 minutes), but restarting the server fixed it. No idea what the problem could be there.

I also rebased this branch on main.

**Comment by carpenterd777** [comment]
Looks good to me. I could not test it using a local server because I can only get the app to download onto my phone when I select "tunnel" in the expo-cli, and when testing the remote server it crashes due to it exceeding the memory allotted by Heroku. we'll have to think of a way to get tesseract to use less memory in the server...

also since I'm the author of this PR I cannot review it lol

**Comment by dyc3** [comment]
We could resize the images locally before uploading, that would save on memory space and network bandwidth.

**Review by dyc3 — APPROVED** [review]

**Pull request merged**
