### PR TITLE
add bash script to download and extract coco dataset

### PR DESCRIPTION
**Pull request by dyc3**

### CODE REVIEW

**Comment by carpenterd777** [comment]
could you add instructions to run the script as part of the setup section in the README?

**Review by carpenterd777 — CHANGES_REQUESTED** [review]
see above comment

**Comment by dyc3** [comment]
Training the model is not going to be necessary for everyone, so it shouldn't be a part of regular project setup. Ideally, we can just train it once, then upload the weights to github, or keep them in the repo. Plus its like a 20gb download, which can take a bit.

**Comment by carpenterd777** [comment]
I see, then in that case could put instructions on how to use the script somewhere else? not necessarily in the README

**Review by carpenterd777 — APPROVED** [review]

**Pull request merged**
