### PR TITLE
Monocle Logo

### PR DESCRIPTION
**Pull request by WBot3000**
Created two versions of a logo. The first one would be used for the app icon, while the one with just the monocle would be used for the button.

### CODE REVIEW

**Comment by dyc3** [comment]
Can you include images here for reference? They don't show up in the contents of the PR.

**Comment by WBot3000** [comment]
Here's the standard one
image

And here's the solo one
image

**Comment by dyc3** [comment]
Idk about inside the button, I think that would look a little weird, but this would definitely work for the splash screen/app icon respectively.

**Comment by carpenterd777** [comment]
Agreed with @dyc3 , would you be able to create a two-tone version of the logo to fit inside of a circular button? I think that would look really good. But these look great too, thanks!

**Comment by WBot3000** [comment]
No problem. Will do.

**Comment by WBot3000** [comment]
I decided to make it gray. If anybody else has a preferred color, let me know.

image

**Review by carpenterd777 — CHANGES_REQUESTED** [review]
could you put all of these in the`src` folder in a folder called `assets`? otherwise looks great!

**Comment by WBot3000** [comment]
Moved the logos into the asset folder. Glad you guys liked them.

**Review by carpenterd777 — APPROVED** [review]

**Comment by carpenterd777** [comment]
Closes #18

**Pull request merged**
