### PR TITLE
Basic flash button is setup, idk about functionality

### LINKED ISSUE #15: Flash button
In the camera view, there should be a lightning-bolt icon with a slash through it. Tapping on this icon turns on the camera flash and changes the icon to a lightning-bolt with no slash. Tapping on this icon again returns the icon to its former state and disables the flash. The flash is disabled by default.

### PR DESCRIPTION
**Pull request by TheShicksinator**
fixes #15

### CODE REVIEW

**Comment by carpenterd777** [comment]
looks like the lint is failing. could you run `yarn lint` and then push again?

**Comment by carpenterd777** [comment]
Also if you put "fixes #15" in the initial comment, merging this pr will close that issue automatically

**Review by dyc3 — CHANGES_REQUESTED** [review]
This is not sufficient to close #15 yet.

See https://docs.expo.dev/versions/latest/sdk/camera/#flashmode for how to turn on the flash

**Comment by carpenterd777** [comment]
> This is not sufficient to close #15 yet.

Yeah unfortunately he's right. If you still wanna merge this in now, you'll have to remove "fixes #15", or implement the functionality. Let us know if you need help!

**Comment by carpenterd777** [comment]
Closing since stale, sorry about that.

**Pull request closed without merging**
